<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-TDT0DRD" failures="2" tests="2" name="Test" time="3.991" errors="0" timestamp="2020-12-10T13:38:48 IST">
  <testcase classname="POC2RestAssured.NewTest" name="getAnotherUser" time="0.015">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at POC2RestAssured.NewTest.getAnotherUser(NewTest.java:63)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at com.sun.proxy.$Proxy2.stop(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 48 stack frames]]>
    </failure>
  </testcase> <!-- getAnotherUser -->
  <testcase classname="POC2RestAssured.NewTest" name="getUser" time="3.936">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at POC2RestAssured.NewTest.getUser(NewTest.java:48)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at com.sun.proxy.$Proxy2.stop(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 48 stack frames]]>
    </failure>
  </testcase> <!-- getUser -->
</testsuite> <!-- Test -->
